id: PDFCF6B3B
initial_creation_type: input
source_metadata:
  title: Praise Series
  language: en
  description: 'A selection of praises (Skt. stotra; Tib. bstod pa) to various Buddhist
    deities and prominent masters (arranged according to subject):'
  volume:
    00fd6b648a5a486e8e18da490fa73767:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: General
    a67b4f39cc1c44e6954fb998c17f4c5d:
      title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of
        the Lineage of Gurus for the Noble Abhidharma'
      parent: Abhidharma Lineage
    551235bb9ed6436697d004a4f7d17efb:
      title: Verses in Praise of the Protector Akṣobhya
      parent: Akṣobhya
    36145acceb434ab680f167741346bc55:
      title: Praise of Noble Avalokiteśvara
      parent: Avalokiteśvara
    703219000f8748c6b1eeab71cc84b30b:
      title: Praise of Noble Avalokiteśvara (Tengyur version)
      parent: Avalokiteśvara
    dae663d6203b43c198b9ad0ecc932db6:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha Śākyamuni
    9ae6e81718b74ffcacf68b367162a495:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha Śākyamuni
    7cc5de79b3e845ca89d1ffb89a6fbc32:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Buddha Śākyamuni
    7c8abb4f74ac4c3ca4076bc4a4ba6452:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha Śākyamuni
    b83d2efb17854b869d8c65d7a5f38d7c:
      title: 'Introduction to the Buddha’s Words: A Praise and Aspiration Related
        to the Words of the Victorious One'
      parent: Buddha's Words
    5c5ed4fc29fa49ec857c4a8f6f383f11:
      title: 'A Beautiful Lotus Garland: In Praise of the Omniscient Lord of Dharma
        Butön Rinchen Drup'
      parent: Butön Rinchen Drup
    94b4a00114c3426683f213f514f014cf:
      title: 'The Swift Infusion of Blessings: In Praise of the Mahāpaṇḍita Candragomin'
      parent: Candragomin
    f90cdd1a73634017b82427b4b14c9bc0:
      title: 'The Melodious Song of Joy: In Praise of the Master Candrakīrti'
      parent: Candrakīrti
    f988df6a521b4242a53394a06beb65ad:
      title: Praise of Candrakīrti
      parent: Candrakīrti
    b57444c878114d55ba9c07de68323514:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Chokgyur Dechen Lingpa
    f1d700c7ae274e2ca7f8ce1d0ff0115a:
      title: A Homage to His Holiness the Dalai Lama
      parent: Fourteenth Dalai Lama
    b6bfb51f560e4949a73e4375188e0d3e:
      title: Verses of Homage
      parent: Fourteenth Dalai Lama
    e5c139df2bab41f1b78a582702571b36:
      title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural
        Traditions
      parent: Ga Rabjampa Kunga Yeshe
    587f969793cc4f2d9773a2c7ec732da2:
      title: 'Cloud Banks of Blessings: Praise and Prayer to the Vajradhara Ngawang
        Lekpa'
      parent: Gatön Ngawang Lekpa
    558e5576c40b4f44aef3579e538c7ed2:
      title: 'Thunderous Melody: In Praise of the Omniscient Gorampa Sonam Senge'
      parent: Gorampa Sonam Senge
    5afb21f1459d42a387ed9ccc0c516485:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Guru Padmasambhava
    2f8a7c782d794412b648d3340b4e678c:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Guru Padmasambhava
    08f9468701434ec39f808ee711ee043f:
      title: A Praise to the Lotus King
      parent: Guru Padmasambhava
    4e01c9cc80d44562ad8b40ebe47e8a9f:
      title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
        Friend Jamyang Gyaltsen'
      parent: Jamyang Gyaltsen
    ee766d3531714c13b0154d24df91d3e4:
      title: In Praise of Jamyang Khyentse Wangpo
      parent: Jamyang Khyentse Wangpo
    cc430e88ac4645d9b5e69407df86b7e7:
      title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
      parent: Jamyang Loter Wangpo
    62229b99c4414dc3aede10ae0cee38ce:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Jigme Lingpa
    9401f4f7c73d407aade457730a62b103:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    0fc7a02f64fa439eb650dab2a5e968d9:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Kṣitigarbha
    c0d552418f264dda9b4fdcd975df62c1:
      title: In Praise of Longchenpa – The Greatness of the Omniscient Longchen Rabjam
      parent: Longchen Rabjam
    de29c96838de4adcae4de5fc7b528032:
      title: In Praise of the Lords of the Three Families
      parent: Lords of the Three Families
    86f9cb7202984c8b95a105c31ce096b9:
      title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik
        Labdrön'
      parent: Machik Labdrön
    5498bd392b254f33b20bd13593435a19:
      title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
      parent: Mandāravā
    d4ca5f5cae9f4276bddcb097e78843d6:
      title: 'The Fresh Saffron Flower: In Praise of Venerable Mañjughoṣa'
      parent: Mañjuśrī
    2b4f377efd494678ab65e929b7c56df3:
      title: 'The Light of Wisdom: Praise to Mañjuśrī'
      parent: Mañjuśrī
    805cc18c51964a85badeb3d200dcf2e6:
      title: 'The Lute of Vajra Harmony: Praise to the Protector Mañjuśrī'
      parent: Mañjuśrī
    6217e7425737478fb5f1576dd986e605:
      title: 'The Swift Infusion of Blessings: In Praise of Mañjughoṣa'
      parent: Mañjuśrī
    732be748b4024dbd8994a48ab7bbd2f7:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Mañjuśrī
    c050f49fecb345bdad1fcaf43043c8dc:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Mañjuśrī
    c6cb3d7fcecb425793f3e2953287e120:
      title: In Praise of the Protector Mañjughoṣa
      parent: Mañjuśrī
    bbc7922830c64c789e484b3561736f1e:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      parent: Mañjuśrī
    22894a7561cf476e97270148421a6413:
      title: Praise to Mañjughoṣa
      parent: Mañjuśrī
    0630a66945cc4422935f17d934357a6e:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    b82bdbb535ee4419914147ca8bdcc6bd:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Mārīcī
    a41b713687494b8bb8dff09beb9c62c5:
      title: In Praise of Jetsün Mila Shepa Dorje
      parent: Milarepa
    85e3f7dcc82441d0b201058e8b9493ca:
      title: 'The Definitive Ascertainment of Tantra: In Praise of the Great Master
        Milarepa'
      parent: Milarepa
    69fcce9baa984b388e024c373013d7c2:
      title: Homage to Milarepa
      parent: Milarepa
    210e500797104ab393caa5b401295a46:
      title: 'The Purifier of Ethical Discipline: An Aspirational Praise to Vajradhara
        Kunga Zangpo'
      parent: Ngorchen Kunga Zangpo
    e627b6d61a09494bac518e4d31e98097:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Patrul Rinpoche
    649e9dc35f3e4d329cb7ba28c168931a:
      title: In Praise of Sönam Palge
      parent: Rogza Sönam Palge
    0baba8f2b59444dd862137c2adbd7082:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    33b68602f3c04eacb07a4e65e9e555ee:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    7d7576401f004231af3518ed07d16cbc:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    85ca5761cbee40bcbf02ed3655fea048:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    ae977c23b298409bb0a03f972fad63e0:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    96fa5ffaec0748c299f3aac0e89839b5:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    d6fc44de751d4890ba215b1ce998018f:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    b957f059f0ff4c388d532929ec58a8cc:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    e9a7a19ee12c44e28be390b009e5a025:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    30ae038854f7479995cb04bca8ebb47c:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    ed34f7f272df49a2a3105f8af4dfacaf:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    8c23e07b96ab445fb513e9079fbc3b4d:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    fedc34c871f84aa2bcc61f29d2ca523b:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    6bff401b5cbd41a4a094433e55c211d7:
      title: Praise to Sakya Paṇḍita
      parent: Sakya Paṇḍita
    3a40c234eaf3484cb8892b5a7aaa0b26:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Śāntarakṣita
    38e89bed15d041a884a78548b5f1414e:
      title: 'Ripples on the Ganges: In Praise of the Goddess Sarasvatī'
      parent: Sarasvatī
    01de4db959a446cfbe7d2361669dffb2:
      title: 'The Melodious Song of Vajra Harmony: In Praise of Red Sarasvatī'
      parent: Sarasvatī
    d27b7f29a1c6430aacfdd9742ebdf1f3:
      title: 'The Sweet Sound of Perfect Joy: In Praise of the Goddess Sarasvatī'
      parent: Sarasvatī
    0b8eef8f372d4f67a7f8dbb8141805c9:
      title: 'Intensely Brilliant Wisdom: In Praise of the Great Elder Smṛtijñāna'
      parent: Smṛtijñānakīrti
    e73ab3d9847447a58853250ad7e29e1b:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tārā
    ce19596f5bf840bf98cbdf4fd4029232:
      title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
      parent: Tārā
    198f956946b04fe29293316cb3348dfc:
      title: 'Flower of Faith: In Praise of Tāranātha, Lord of Secrets'
      parent: Tāranātha
    dede0c3d2aba40e99e087264913794a2:
      title: 'A Blossoming of the Intellect: In Praise of the Great Pioneer Thönmi
        Sambhoṭa'
      parent: Thönmi Sambhoṭa
    cec1616eda7946f3aa918dd251553f05:
      title: In Praise of the Three Jewels
      parent: Three Jewels
    9b40305002384429ae165227ee44aa92:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Tri Songdetsen
    ab0f512d877849b2a138d3a39d21386d:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Tsongkhapa Lobzang Drakpa
    36d035cfa16f4581affb870e454463a5:
      title: A Song of Innermost Praise to Vajrasattva
      parent: Vajrasattva
    e49572ab52674ac48c57e692afc8a64a:
      title: 'Wish-Granting Provision of Twofold Accomplishment: A Praise of Vajrasattva'
      parent: Vajrasattva
    ba126539018e4a14812af8f161b8cc2a:
      title: In Praise of Glorious Vajrasattva
      parent: Vajrasattva
    0efcbab60d2d4d1f95dada169c47bfbb:
      title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
        of the Realm of Holy Nāro Khecarī'
      parent: Vajrayoginī
    6c9caaedac26481693e95662b4ef192f:
      title: 'The Hero''s Bellowing Laughter: In Praise of the Lord of Yogins'
      parent: Virūpa
created_at: '2022-03-01T05:11:17.789629'
last_modified_at: '2022-03-01T05:11:17.789635'
